export const morbilidades: string[] = [
  'HTA',
  'DM tipo I',
  'DM tipo II',
  'Hipotiroidismo',
  'Asma',
  'Dislipidemia',
  'Enf.Digestivas',
  'Enf.Cardiacas',
  'Enf.Neurológicas',
  'Sist.Endocrino',
  'Sist.Respiratorio',
  'Sist.Urinario',
  'Tiroides',
  'Antec.Salud Mental',
  'Epilepsia',
  'Gota',
  'Otras',
];

export const drogasIlegales: string[] = [
  'Cannabis',
  'Cocaína',
  'Pasta Base',
  'Benzodiacepinas',
  'Hongos alucinógenos',
  'LSD',
];

export const viaAdministacion: string[] = [
  'Oral (Por Boca)',
  'Tópica (Por Piel)',
  'Intramuscular (Inyección)',
  'Inhalatoria (Por boca y/o nariz)',
  'Oftalmológica (Por ojos)',
  'Vaginal',
  'Rectal (Por ano)',
  'Ótica (Por oídos)',
  'Sublingual (Por debajo de la lengua)',
  'Intravenosa',
  'Subcutánea',
];

export const formAtenValues: any = {
  mconsulta_ad: '',
  aproxima_ad: '',
  deam_ad: '',
  facie_ad: '',
  piel_ad: '',
  emental_ad: '',
  aden_ad: '',
  cab_ad: '',
  cuello_ad: '',
  torax_ad: '',
  mamas_ad: '',
  corazon_ad: '',
  pulmones_ad: '',
  abd_ad: '',
  col_ad: '',
  eess_ad: '',
  eeii_ad: '',
  geni_ad: '',
  eneuro_ad: '',
  trectal_ad: '',
  dgcie10_ad: '',
  dgsec_ad: '',
  obsdg_ad: '',
  planest_ad: [{ value: '' }],
  med_ad: [{ medicamento: '', via: '', dosis: '', hrs: null, dias: null }],
  ind_ad: '',
  intern: [{ value: '' }],
  id_doctor: '',
};

export const formAntecValues: any = {
  morb: [],
  trat_morb: '',
  ant_quirurgico: '',
  alergias: '',
  inmuni: '',
  //Inicio mujer
  menarquia: '',
  fecha_ult_regla: '',
  g_ad: '',
  p_ad: '',
  a_ad: '',
  mac_ad: '',
  menopausia: '',
  papanicolaou: '',
  //Fin mujer
  tabaco: '',
  cant_cig: '',
  anios_cig: '',
  alcohol: '',
  cant_alcohol: '',
  tiempo_alcohol: '',
  drogas: [],
  otra_droga: '',
  ejercicio: '',
  cant_ejercicio: '',
  min_ejercicio: '',
  medic_habitual: '',
  ocupacion: '',
  estado_civil: '',
  niv_educacion: '',
  antec_familiar: '',
  antec_social: '',
};
